# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run a databricks notebook
      uses: databricks/run-notebook@v0
      with:
       local-notebook-path: .github/integration_test/notebook.py
       databricks-host: https://e2-dogfood.staging.cloud.databricks.com
       databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
       git-commit: ${{ github.sha }}
       existing-cluster-id: "1118-013127-82wynr8t"

